// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUILVJcvzQi6pX1SaqTIfEG9tNzhWV9GA',
    appId: '1:1053006820099:web:d3525742063cfc66dfef36',
    messagingSenderId: '1053006820099',
    projectId: 'notesapp-1a903',
    authDomain: 'notesapp-1a903.firebaseapp.com',
    storageBucket: 'notesapp-1a903.appspot.com',
    measurementId: 'G-1BNZ8JX41T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx1qA-19ath1NePVFRVAIeDgpeYCazkLs',
    appId: '1:1053006820099:android:93573fc40ef04d2edfef36',
    messagingSenderId: '1053006820099',
    projectId: 'notesapp-1a903',
    storageBucket: 'notesapp-1a903.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGkNYXIBZTCzn4Ih_G4RV0Lvecbi6QWtk',
    appId: '1:1053006820099:ios:ff5037ec7dd561dbdfef36',
    messagingSenderId: '1053006820099',
    projectId: 'notesapp-1a903',
    storageBucket: 'notesapp-1a903.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGkNYXIBZTCzn4Ih_G4RV0Lvecbi6QWtk',
    appId: '1:1053006820099:ios:3e0f742d28944f15dfef36',
    messagingSenderId: '1053006820099',
    projectId: 'notesapp-1a903',
    storageBucket: 'notesapp-1a903.appspot.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
